### ISSUE TITLE
Error bel2rdf 

### ISSUE THREAD

**Issue by berenicew** [OpenBEL/bel.rb#130]
Dear,

I am running the bel2rdf tool. I tried first the tool with small corpus and it proceed the file very well, but when using another BEL file, I get an error.
Please find below the stack trace of the error

Best regards,

/home/berenice/gitrep/bel.rb/bin/bel2rdf.rb --bel BEL_ALXN_orig_1_0.bel --format turtle > BEL_ALXN_orig_1_0.ttl
/home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/syntax/undefined_annotation_value.rb:46:in `map': undefined method `identifier' for nil:NilClass (NoMethodError)
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:33:in `block (3 levels) in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:32:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:32:in `flat_map'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:32:in `block (2 levels) in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/parsers/ast/node.rb:107:in `traverse'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:31:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:31:in `flat_map'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:31:in `block in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/state_aggregator.rb:25:in `block in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/first_node.rb:13:in `block in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_filter.rb:15:in `block in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:63:in `block in each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `yield'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each_line'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_generator.rb:52:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/ast_filter.rb:13:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/filter.rb:28:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/first_node.rb:12:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/state_aggregator.rb:19:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/validator.rb:30:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel_parser/script/nanopub_mapper.rb:26:in `each'
	from /home/berenice/.rvm/gems/ruby-2.2.6/gems/bel_parser-1.0.8/lib/bel/translator/plugins/bel_script/reader.rb:34:in `each'
	from /home/berenice/gitrep/bel.rb/lib/bel/translator/plugins/rdf2/translator.rb:30:in `write'
	from /home/berenice/gitrep/bel.rb/lib/bel/translate.rb:53:in `translate'
	from /home/berenice/gitrep/bel.rb/bin/bel2rdf.rb:108:in `<main>'

**Comment by berenicew** [comment]
Hi, 

Please find more informaion, with a simple example.
The problem happened when referencing openBEL annotation files. Please find bealow a simple bel file that generate the error


```samplebel
##################################################################################
# Document Properties Section
###############################################################################
# Definitions Section
DEFINE ANNOTATION Species AS URL "https://resources.openbel.org/belframework/20131211/annotation/species-taxonomy-id.belanno"
##################################################################################
# Statements Section
SET Species = "9606"
```


And the command line bel2rdf.rb --bel sample.bel --format turtle > sample.ttl
